

spring:
  application:
    name: hystrix-feign
server:
  port: 8106
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka1:8098/eureka/,http://eureka2:8099/eureka/

hystrix:
  metrics:
    enabled: true